name: consuming_rest_api
description: Consuming REST API using Provider, Getit , Dio
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio:
  dartz:
  get_it:
  injectable:
  provider:
  internet_connection_checker:
  equatable:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  injectable_generator:
  flutter_gen_runner:

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

